<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.557">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Methods in Humanities Analytics - 9&nbsp; ANOVA and R²: Comparing Groups and Explaining Variance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../tutorials/cluster-analysis.html" rel="next">
<link href="../tutorials/topic-modeling.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/text_analysis.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Methods in Humanities Analytics</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
    <a href="https://github.com/browndw/humanities_analytics" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../tutorials/categorical-variables.html">Advanced Analysis</a></li><li class="breadcrumb-item"><a href="../tutorials/categorical-variables.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">ANOVA and R²: Comparing Groups and Explaining Variance</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/sentiment-and-syuzhet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Texts, Algorithms, and Black-Boxes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/corpus-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Corpus Basics: Tokenization and Processing Pipelines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/spacy-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">NLP Processing with spaCy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/frequency-and-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Distributions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Core Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/keyness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Keyness</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/collocations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Collocations and N-grams</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Time Series Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/topic-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Topic Modeling</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Advanced Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/categorical-variables.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">ANOVA and R²: Comparing Groups and Explaining Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/cluster-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Clustering Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/correlations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Correlation and Multi-Collinearity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/multi-dimensional-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Multi-Dimensional Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/contextual-embeddings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Contextual Embeddings and Transformers</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Applications</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/classification-federalist-papers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Classification &amp; Authorship Attribution</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Reports</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reports/cbe_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Coffee Break Experiment #1: From Curiosity to Visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reports/cbe_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Coffee Break Experiment #2: From Results to Research</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reports/cbe_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Coffee Break Experiment #3: Final Project Pilot Study</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reports/final-project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Final Project: Independent Corpus Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reports/statistical-reporting-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical Reporting Guide</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Course Resources</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/using-colab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Using Google Colab</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python Packages for This Course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Data Resources</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">9.1</span> Introduction</a></li>
  <li><a href="#core-concepts" id="toc-core-concepts" class="nav-link" data-scroll-target="#core-concepts"><span class="header-section-number">9.2</span> Core Concepts</a>
  <ul class="collapse">
  <li><a href="#the-research-question" id="toc-the-research-question" class="nav-link" data-scroll-target="#the-research-question"><span class="header-section-number">9.2.1</span> The Research Question</a></li>
  <li><a href="#anova-analysis-of-variance" id="toc-anova-analysis-of-variance" class="nav-link" data-scroll-target="#anova-analysis-of-variance"><span class="header-section-number">9.2.2</span> ANOVA: Analysis of Variance</a></li>
  <li><a href="#r²-coefficient-of-determination" id="toc-r²-coefficient-of-determination" class="nav-link" data-scroll-target="#r²-coefficient-of-determination"><span class="header-section-number">9.2.3</span> R²: Coefficient of Determination</a></li>
  <li><a href="#η²-eta-squared-anovas-r²" id="toc-η²-eta-squared-anovas-r²" class="nav-link" data-scroll-target="#η²-eta-squared-anovas-r²"><span class="header-section-number">9.2.4</span> η² (Eta-Squared): ANOVA’s R²</a></li>
  </ul></li>
  <li><a href="#understanding-the-mathematics" id="toc-understanding-the-mathematics" class="nav-link" data-scroll-target="#understanding-the-mathematics"><span class="header-section-number">9.3</span> Understanding the Mathematics</a>
  <ul class="collapse">
  <li><a href="#variance-decomposition" id="toc-variance-decomposition" class="nav-link" data-scroll-target="#variance-decomposition"><span class="header-section-number">9.3.1</span> Variance Decomposition</a></li>
  <li><a href="#computing-sum-of-squares" id="toc-computing-sum-of-squares" class="nav-link" data-scroll-target="#computing-sum-of-squares"><span class="header-section-number">9.3.2</span> Computing Sum of Squares</a></li>
  <li><a href="#f-statistic-the-anova-test" id="toc-f-statistic-the-anova-test" class="nav-link" data-scroll-target="#f-statistic-the-anova-test"><span class="header-section-number">9.3.3</span> F-Statistic: The ANOVA Test</a></li>
  <li><a href="#computing-r²-and-η²" id="toc-computing-r²-and-η²" class="nav-link" data-scroll-target="#computing-r²-and-η²"><span class="header-section-number">9.3.4</span> Computing R² and η²</a></li>
  </ul></li>
  <li><a href="#anova-in-practice-example" id="toc-anova-in-practice-example" class="nav-link" data-scroll-target="#anova-in-practice-example"><span class="header-section-number">9.4</span> ANOVA in Practice: Example</a>
  <ul class="collapse">
  <li><a href="#generate-example-data" id="toc-generate-example-data" class="nav-link" data-scroll-target="#generate-example-data"><span class="header-section-number">9.4.1</span> Generate Example Data</a></li>
  <li><a href="#descriptive-statistics-by-group" id="toc-descriptive-statistics-by-group" class="nav-link" data-scroll-target="#descriptive-statistics-by-group"><span class="header-section-number">9.4.2</span> Descriptive Statistics by Group</a></li>
  <li><a href="#visualize-group-differences" id="toc-visualize-group-differences" class="nav-link" data-scroll-target="#visualize-group-differences"><span class="header-section-number">9.4.3</span> Visualize Group Differences</a></li>
  <li><a href="#perform-one-way-anova" id="toc-perform-one-way-anova" class="nav-link" data-scroll-target="#perform-one-way-anova"><span class="header-section-number">9.4.4</span> Perform One-Way ANOVA</a></li>
  <li><a href="#compute-sum-of-squares-manually" id="toc-compute-sum-of-squares-manually" class="nav-link" data-scroll-target="#compute-sum-of-squares-manually"><span class="header-section-number">9.4.5</span> Compute Sum of Squares Manually</a></li>
  <li><a href="#compute-r²-η²" id="toc-compute-r²-η²" class="nav-link" data-scroll-target="#compute-r²-η²"><span class="header-section-number">9.4.6</span> Compute R² (η²)</a></li>
  <li><a href="#compute-f-statistic-manually" id="toc-compute-f-statistic-manually" class="nav-link" data-scroll-target="#compute-f-statistic-manually"><span class="header-section-number">9.4.7</span> Compute F-Statistic Manually</a></li>
  <li><a href="#anova-table" id="toc-anova-table" class="nav-link" data-scroll-target="#anova-table"><span class="header-section-number">9.4.8</span> ANOVA Table</a></li>
  </ul></li>
  <li><a href="#post-hoc-tests-which-groups-differ" id="toc-post-hoc-tests-which-groups-differ" class="nav-link" data-scroll-target="#post-hoc-tests-which-groups-differ"><span class="header-section-number">9.5</span> Post-Hoc Tests: Which Groups Differ?</a>
  <ul class="collapse">
  <li><a href="#the-multiple-comparisons-problem" id="toc-the-multiple-comparisons-problem" class="nav-link" data-scroll-target="#the-multiple-comparisons-problem"><span class="header-section-number">9.5.1</span> The Multiple Comparisons Problem</a></li>
  <li><a href="#tukeys-hsd-honestly-significant-difference" id="toc-tukeys-hsd-honestly-significant-difference" class="nav-link" data-scroll-target="#tukeys-hsd-honestly-significant-difference"><span class="header-section-number">9.5.2</span> Tukey’s HSD (Honestly Significant Difference)</a></li>
  <li><a href="#visualize-post-hoc-results" id="toc-visualize-post-hoc-results" class="nav-link" data-scroll-target="#visualize-post-hoc-results"><span class="header-section-number">9.5.3</span> Visualize Post-Hoc Results</a></li>
  <li><a href="#bonferroni-correction-alternative" id="toc-bonferroni-correction-alternative" class="nav-link" data-scroll-target="#bonferroni-correction-alternative"><span class="header-section-number">9.5.4</span> Bonferroni Correction (Alternative)</a></li>
  </ul></li>
  <li><a href="#anova-in-mda-example" id="toc-anova-in-mda-example" class="nav-link" data-scroll-target="#anova-in-mda-example"><span class="header-section-number">9.6</span> ANOVA in MDA: Example</a>
  <ul class="collapse">
  <li><a href="#load-mda-results" id="toc-load-mda-results" class="nav-link" data-scroll-target="#load-mda-results"><span class="header-section-number">9.6.1</span> Load MDA Results</a></li>
  <li><a href="#test-each-dimension" id="toc-test-each-dimension" class="nav-link" data-scroll-target="#test-each-dimension"><span class="header-section-number">9.6.2</span> Test Each Dimension</a></li>
  <li><a href="#visualize-dimension-performance" id="toc-visualize-dimension-performance" class="nav-link" data-scroll-target="#visualize-dimension-performance"><span class="header-section-number">9.6.3</span> Visualize Dimension Performance</a></li>
  </ul></li>
  <li><a href="#assumptions-and-diagnostics" id="toc-assumptions-and-diagnostics" class="nav-link" data-scroll-target="#assumptions-and-diagnostics"><span class="header-section-number">9.7</span> Assumptions and Diagnostics</a>
  <ul class="collapse">
  <li><a href="#independence" id="toc-independence" class="nav-link" data-scroll-target="#independence"><span class="header-section-number">9.7.1</span> 1. Independence</a></li>
  <li><a href="#normality" id="toc-normality" class="nav-link" data-scroll-target="#normality"><span class="header-section-number">9.7.2</span> 2. Normality</a></li>
  <li><a href="#homogeneity-of-variance" id="toc-homogeneity-of-variance" class="nav-link" data-scroll-target="#homogeneity-of-variance"><span class="header-section-number">9.7.3</span> 3. Homogeneity of Variance</a></li>
  <li><a href="#welchs-anova-robust-alternative" id="toc-welchs-anova-robust-alternative" class="nav-link" data-scroll-target="#welchs-anova-robust-alternative"><span class="header-section-number">9.7.4</span> Welch’s ANOVA (Robust Alternative)</a></li>
  </ul></li>
  <li><a href="#reporting-results" id="toc-reporting-results" class="nav-link" data-scroll-target="#reporting-results"><span class="header-section-number">9.8</span> Reporting Results</a>
  <ul class="collapse">
  <li><a href="#apa-style" id="toc-apa-style" class="nav-link" data-scroll-target="#apa-style"><span class="header-section-number">9.8.1</span> APA Style</a></li>
  <li><a href="#in-tables" id="toc-in-tables" class="nav-link" data-scroll-target="#in-tables"><span class="header-section-number">9.8.2</span> In Tables</a></li>
  </ul></li>
  <li><a href="#connections-to-other-methods" id="toc-connections-to-other-methods" class="nav-link" data-scroll-target="#connections-to-other-methods"><span class="header-section-number">9.9</span> Connections to Other Methods</a>
  <ul class="collapse">
  <li><a href="#anova-and-mda" id="toc-anova-and-mda" class="nav-link" data-scroll-target="#anova-and-mda"><span class="header-section-number">9.9.1</span> ANOVA and MDA</a></li>
  <li><a href="#anova-and-classification" id="toc-anova-and-classification" class="nav-link" data-scroll-target="#anova-and-classification"><span class="header-section-number">9.9.2</span> ANOVA and Classification</a></li>
  <li><a href="#anova-and-regression" id="toc-anova-and-regression" class="nav-link" data-scroll-target="#anova-and-regression"><span class="header-section-number">9.9.3</span> ANOVA and Regression</a></li>
  <li><a href="#anova-and-time-series" id="toc-anova-and-time-series" class="nav-link" data-scroll-target="#anova-and-time-series"><span class="header-section-number">9.9.4</span> ANOVA and Time Series</a></li>
  </ul></li>
  <li><a href="#methodological-considerations" id="toc-methodological-considerations" class="nav-link" data-scroll-target="#methodological-considerations"><span class="header-section-number">9.10</span> Methodological Considerations</a>
  <ul class="collapse">
  <li><a href="#sample-size" id="toc-sample-size" class="nav-link" data-scroll-target="#sample-size"><span class="header-section-number">9.10.1</span> 1. Sample Size</a></li>
  <li><a href="#multiple-testing" id="toc-multiple-testing" class="nav-link" data-scroll-target="#multiple-testing"><span class="header-section-number">9.10.2</span> 2. Multiple Testing</a></li>
  <li><a href="#practical-vs.-statistical-significance" id="toc-practical-vs.-statistical-significance" class="nav-link" data-scroll-target="#practical-vs.-statistical-significance"><span class="header-section-number">9.10.3</span> 3. Practical vs.&nbsp;Statistical Significance</a></li>
  <li><a href="#nested-data" id="toc-nested-data" class="nav-link" data-scroll-target="#nested-data"><span class="header-section-number">9.10.4</span> 4. Nested Data</a></li>
  </ul></li>
  <li><a href="#ethical-considerations" id="toc-ethical-considerations" class="nav-link" data-scroll-target="#ethical-considerations"><span class="header-section-number">9.11</span> Ethical Considerations</a>
  <ul class="collapse">
  <li><a href="#p-hacking" id="toc-p-hacking" class="nav-link" data-scroll-target="#p-hacking"><span class="header-section-number">9.11.1</span> 1. P-Hacking</a></li>
  <li><a href="#harking-hypothesizing-after-results-known" id="toc-harking-hypothesizing-after-results-known" class="nav-link" data-scroll-target="#harking-hypothesizing-after-results-known"><span class="header-section-number">9.11.2</span> 2. HARKing (Hypothesizing After Results Known)</a></li>
  <li><a href="#overgeneralizing" id="toc-overgeneralizing" class="nav-link" data-scroll-target="#overgeneralizing"><span class="header-section-number">9.11.3</span> 3. Overgeneralizing</a></li>
  <li><a href="#ignoring-context" id="toc-ignoring-context" class="nav-link" data-scroll-target="#ignoring-context"><span class="header-section-number">9.11.4</span> 4. Ignoring Context</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">9.12</span> Summary</a></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading"><span class="header-section-number">9.13</span> Further Reading</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/browndw/humanities_analytics/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../tutorials/categorical-variables.html">Advanced Analysis</a></li><li class="breadcrumb-item"><a href="../tutorials/categorical-variables.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">ANOVA and R²: Comparing Groups and Explaining Variance</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">ANOVA and R²: Comparing Groups and Explaining Variance</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">9.1</span> Introduction</h2>
<p>After performing dimension reduction (like PCA or Factor Analysis in <a href="#sec-mda">MDA</a>), a critical question emerges: <strong>Do the dimensions we’ve extracted actually distinguish our text categories?</strong></p>
<p>For example, if Multi-Dimensional Analysis produces a dimension labeled “Involved vs.&nbsp;Informational Production,” we need to test:</p>
<ul>
<li>Do fiction texts score significantly higher than academic texts on this dimension?</li>
<li>How much of the variation in dimension scores is explained by genre?</li>
<li>Are the differences large enough to matter, or just statistically detectable?</li>
</ul>
<p><strong>ANOVA</strong> (Analysis of Variance) and <strong>R²</strong> (R-squared, coefficient of determination) answer these questions. This tutorial explains:</p>
<ol type="1">
<li><strong>What these statistics measure</strong> and why they matter</li>
<li><strong>Where the numbers come from</strong> (the mathematical foundations)</li>
<li><strong>How to interpret them</strong> in the context of text analysis and MDA</li>
<li><strong>How to compute and report them</strong> using Python</li>
</ol>
</section>
<section id="core-concepts" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="core-concepts"><span class="header-section-number">9.2</span> Core Concepts</h2>
<section id="the-research-question" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="the-research-question"><span class="header-section-number">9.2.1</span> The Research Question</h3>
<p>Imagine you’ve extracted dimension scores for 500 documents across 15 genres. You hypothesize that <strong>Genre A</strong> differs from <strong>Genre B</strong> on Dimension 1. How do you test this?</p>
<p><strong>Three related questions:</strong></p>
<ol type="1">
<li><strong>Are the means different?</strong> ANOVA tests if group means differ more than expected by chance</li>
<li><strong>How much variance is explained?</strong> R² quantifies what proportion of total variance is due to group membership</li>
<li><strong>Is the effect meaningful?</strong> Effect sizes (like η²) indicate practical significance beyond statistical significance</li>
</ol>
</section>
<section id="anova-analysis-of-variance" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="anova-analysis-of-variance"><span class="header-section-number">9.2.2</span> ANOVA: Analysis of Variance</h3>
<p><strong>ANOVA</strong> is a statistical test that compares means across two or more groups by analyzing variance.</p>
<p><strong>Core insight</strong>: Variance can be partitioned into:</p>
<ul>
<li><strong>Between-group variance</strong>: How much do group means differ from the overall mean?</li>
<li><strong>Within-group variance</strong>: How much do individual observations differ from their group mean?</li>
</ul>
<p>If between-group variance is much larger than within-group variance, groups genuinely differ (not just random variation).</p>
<p><strong>Example</strong>: Dimension 1 scores for three genres:</p>
<ul>
<li><strong>Fiction</strong>: Mean = 15, scores range 10-20</li>
<li><strong>Academic</strong>: Mean = -12, scores range -18 to -6<br>
</li>
<li><strong>News</strong>: Mean = 2, scores range -5 to 9</li>
</ul>
<p>ANOVA tests: Is the variation between these three means (15 vs.&nbsp;-12 vs.&nbsp;2) greater than the variation within each group?</p>
</section>
<section id="r²-coefficient-of-determination" class="level3" data-number="9.2.3">
<h3 data-number="9.2.3" class="anchored" data-anchor-id="r²-coefficient-of-determination"><span class="header-section-number">9.2.3</span> R²: Coefficient of Determination</h3>
<p><strong>R²</strong> (R-squared) measures <strong>proportion of variance explained</strong> by the grouping variable (genre).</p>
<ul>
<li><strong>R² = 0</strong>: Genre explains 0% of variance (dimension scores are identical across genres)</li>
<li><strong>R² = 1</strong>: Genre explains 100% of variance (all variation is due to genre differences, no within-group variation)</li>
<li><strong>R² = 0.35</strong>: Genre explains 35% of variance (remaining 65% is individual variation within genres)</li>
</ul>
<p><strong>Interpretation</strong>: R² = 0.35 means if you know a text’s genre, you can explain 35% of the variation in its dimension score. The other 65% comes from other factors (author, topic, style).</p>
<p><strong>In MDA context</strong>: After extracting dimensions, R² tells you how well those dimensions differentiate your categories. High R² (&gt; 0.25) indicates dimensions are strong category markers.</p>
</section>
<section id="η²-eta-squared-anovas-r²" class="level3" data-number="9.2.4">
<h3 data-number="9.2.4" class="anchored" data-anchor-id="η²-eta-squared-anovas-r²"><span class="header-section-number">9.2.4</span> η² (Eta-Squared): ANOVA’s R²</h3>
<p><strong>η²</strong> (eta-squared) is the R² for ANOVA: proportion of total variance explained by group membership.</p>
<p><strong>Formula</strong>: η² = SS_between / SS_total</p>
<p><strong>Equivalent to R²</strong> in one-way ANOVA (single grouping variable like “genre”).</p>
<p><strong>Effect size benchmarks</strong> (Cohen, 1988):</p>
<ul>
<li><strong>η² = 0.01</strong> (1%): Small effect</li>
<li><strong>η² = 0.06</strong> (6%): Medium effect</li>
<li><strong>η² = 0.14</strong> (14%): Large effect</li>
</ul>
<p><strong>In text analysis</strong>: η² = 0.20 for a dimension means 20% of linguistic variation is explained by genre—a strong, meaningful pattern (well above Cohen’s “large” threshold).</p>
</section>
</section>
<section id="understanding-the-mathematics" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="understanding-the-mathematics"><span class="header-section-number">9.3</span> Understanding the Mathematics</h2>
<section id="variance-decomposition" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="variance-decomposition"><span class="header-section-number">9.3.1</span> Variance Decomposition</h3>
<p>Total variance in dimension scores can be partitioned:</p>
<p><strong>SS_total = SS_between + SS_within</strong></p>
<p>Where:</p>
<ul>
<li><strong>SS_total</strong>: Total sum of squares (total variance across all observations)</li>
<li><strong>SS_between</strong>: Between-group sum of squares (variance due to group differences)</li>
<li><strong>SS_within</strong>: Within-group sum of squares (variance within groups, “error”)</li>
</ul>
<p><strong>Intuition</strong>: Imagine dimension scores for 50 texts (10 each from 5 genres). Total variance = how much all 50 scores vary. This variance has two sources:</p>
<ol type="1">
<li><strong>Between-group</strong>: The 5 genre means differ (Fiction = +15, Academic = -12, etc.)</li>
<li><strong>Within-group</strong>: Within Fiction, some texts score 12, others 18 (variation around Fiction’s mean)</li>
</ol>
<p>ANOVA tests if source #1 (between-group) is larger than expected if groups were identical.</p>
</section>
<section id="computing-sum-of-squares" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="computing-sum-of-squares"><span class="header-section-number">9.3.2</span> Computing Sum of Squares</h3>
<section id="ss_total-total-sum-of-squares" class="level4" data-number="9.3.2.1">
<h4 data-number="9.3.2.1" class="anchored" data-anchor-id="ss_total-total-sum-of-squares"><span class="header-section-number">9.3.2.1</span> SS_total: Total Sum of Squares</h4>
<p><strong>Formula</strong>:</p>
<p><span class="math display">\[SS_{total} = \sum_{i=1}^{n}(x_i - \bar{x})^2\]</span></p>
<p>Where: - <span class="math inline">\(x_i\)</span> = individual observation (dimension score for text <em>i</em>) - <span class="math inline">\(\bar{x}\)</span> = grand mean (average score across all texts) - <span class="math inline">\(n\)</span> = total number of observations</p>
<p><strong>Interpretation</strong>: Sum of squared deviations from the overall mean. Measures total variation in the data.</p>
<p><strong>Example</strong>:</p>
<pre><code>Scores: [15, 12, -10, -14, 3]
Grand mean: (15+12-10-14+3)/5 = 1.2

SS_total = (15-1.2)² + (12-1.2)² + (-10-1.2)² + (-14-1.2)² + (3-1.2)²
         = 190.44 + 116.64 + 125.44 + 231.04 + 3.24
         = 666.8</code></pre>
</section>
<section id="ss_between-between-group-sum-of-squares" class="level4" data-number="9.3.2.2">
<h4 data-number="9.3.2.2" class="anchored" data-anchor-id="ss_between-between-group-sum-of-squares"><span class="header-section-number">9.3.2.2</span> SS_between: Between-Group Sum of Squares</h4>
<p><strong>Formula</strong>:</p>
<p><span class="math display">\[SS_{between} = \sum_{j=1}^{k} n_j(\bar{x}_j - \bar{x})^2\]</span></p>
<p>Where: - <span class="math inline">\(k\)</span> = number of groups (genres) - <span class="math inline">\(n_j\)</span> = number of observations in group <em>j</em> - <span class="math inline">\(\bar{x}_j\)</span> = mean of group <em>j</em> - <span class="math inline">\(\bar{x}\)</span> = grand mean</p>
<p><strong>Interpretation</strong>: Weighted sum of squared differences between group means and grand mean. Measures variation due to group differences.</p>
<p><strong>Example</strong> (3 groups, 2 texts each):</p>
<pre><code>Group A: [14, 16], mean = 15
Group B: [-13, -11], mean = -12
Group C: [1, 3], mean = 2
Grand mean = 1.0

SS_between = 2×(15-1)² + 2×(-12-1)² + 2×(2-1)²
           = 2×196 + 2×169 + 2×1
           = 392 + 338 + 2
           = 732</code></pre>
</section>
<section id="ss_within-within-group-sum-of-squares" class="level4" data-number="9.3.2.3">
<h4 data-number="9.3.2.3" class="anchored" data-anchor-id="ss_within-within-group-sum-of-squares"><span class="header-section-number">9.3.2.3</span> SS_within: Within-Group Sum of Squares</h4>
<p><strong>Formula</strong>:</p>
<p><span class="math display">\[SS_{within} = \sum_{j=1}^{k}\sum_{i=1}^{n_j}(x_{ij} - \bar{x}_j)^2\]</span></p>
<p>Where: - <span class="math inline">\(x_{ij}\)</span> = observation <em>i</em> in group <em>j</em> - <span class="math inline">\(\bar{x}_j\)</span> = mean of group <em>j</em></p>
<p><strong>Interpretation</strong>: Sum of squared deviations from each observation to its group mean. Measures variation within groups (not explained by group membership).</p>
<p><strong>Example</strong> (same 3 groups):</p>
<pre><code>Group A: [14, 16], mean = 15
  SS_A = (14-15)² + (16-15)² = 1 + 1 = 2

Group B: [-13, -11], mean = -12
  SS_B = (-13-(-12))² + (-11-(-12))² = 1 + 1 = 2

Group C: [1, 3], mean = 2
  SS_C = (1-2)² + (3-2)² = 1 + 1 = 2

SS_within = 2 + 2 + 2 = 6</code></pre>
<p><strong>Check</strong>: SS_total should equal SS_between + SS_within (within rounding error).</p>
</section>
</section>
<section id="f-statistic-the-anova-test" class="level3" data-number="9.3.3">
<h3 data-number="9.3.3" class="anchored" data-anchor-id="f-statistic-the-anova-test"><span class="header-section-number">9.3.3</span> F-Statistic: The ANOVA Test</h3>
<p>ANOVA computes an <strong>F-statistic</strong> that compares between-group to within-group variance:</p>
<p><strong>Formula</strong>:</p>
<p><span class="math display">\[F = \frac{MS_{between}}{MS_{within}} = \frac{SS_{between}/(k-1)}{SS_{within}/(n-k)}\]</span></p>
<p>Where:</p>
<ul>
<li><strong>MS_between</strong> = Mean square between groups (variance between groups)
<ul>
<li><span class="math inline">\(MS_{between} = SS_{between} / df_{between}\)</span></li>
<li><span class="math inline">\(df_{between} = k - 1\)</span> (degrees of freedom: number of groups - 1)</li>
</ul></li>
<li><strong>MS_within</strong> = Mean square within groups (variance within groups, “error”)
<ul>
<li><span class="math inline">\(MS_{within} = SS_{within} / df_{within}\)</span></li>
<li><span class="math inline">\(df_{within} = n - k\)</span> (degrees of freedom: total observations - number of groups)</li>
</ul></li>
</ul>
<p><strong>Interpretation</strong>:</p>
<ul>
<li><strong>F ≈ 1</strong>: Between-group variance equals within-group variance (groups don’t differ)</li>
<li><strong>F &gt;&gt; 1</strong>: Between-group variance much larger (groups genuinely differ)</li>
<li><strong>P-value</strong>: Probability of observing F this large if groups were identical (p &lt; 0.05 = significant)</li>
</ul>
<p><strong>Example</strong>:</p>
<pre><code>From earlier: SS_between = 732, SS_within = 6
Groups k = 3, total n = 6

MS_between = 732 / (3-1) = 732 / 2 = 366
MS_within = 6 / (6-3) = 6 / 3 = 2

F = 366 / 2 = 183</code></pre>
<p><strong>Interpretation</strong>: Between-group variance is 183× larger than within-group variance. Extremely strong evidence that groups differ (p-value would be tiny).</p>
</section>
<section id="computing-r²-and-η²" class="level3" data-number="9.3.4">
<h3 data-number="9.3.4" class="anchored" data-anchor-id="computing-r²-and-η²"><span class="header-section-number">9.3.4</span> Computing R² and η²</h3>
<p>Once we have sum of squares, R² and η² are straightforward:</p>
<p><strong>Formula</strong>:</p>
<p><span class="math display">\[R^2 = \eta^2 = \frac{SS_{between}}{SS_{total}}\]</span></p>
<p><strong>Example</strong>:</p>
<pre><code>SS_between = 732
SS_total = SS_between + SS_within = 732 + 6 = 738

η² = 732 / 738 = 0.992 (99.2%)</code></pre>
<p><strong>Interpretation</strong>: Genre explains 99.2% of variance in dimension scores. Nearly perfect separation (unrealistically high—real text data usually shows 15-50%).</p>
<p><strong>Adjusted η²</strong> (accounts for sample size):</p>
<p><span class="math display">\[\eta^2_{adj} = 1 - \frac{SS_{within}/(n-k)}{SS_{total}/(n-1)}\]</span></p>
<p>More conservative than η², penalizes models with many groups relative to sample size.</p>
</section>
</section>
<section id="anova-in-practice-example" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="anova-in-practice-example"><span class="header-section-number">9.4</span> ANOVA in Practice: Example</h2>
<p>Let’s test if genres differ on a dimension extracted from linguistic features:</p>
<section id="generate-example-data" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="generate-example-data"><span class="header-section-number">9.4.1</span> Generate Example Data</h3>
<div id="d9599196" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate dimension scores for 150 texts across 3 genres</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Fiction: High positive scores (involved production)</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>fiction_scores <span class="op">=</span> np.random.normal(loc<span class="op">=</span><span class="dv">15</span>, scale<span class="op">=</span><span class="dv">5</span>, size<span class="op">=</span><span class="dv">50</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Academic: High negative scores (informational production)</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>academic_scores <span class="op">=</span> np.random.normal(loc<span class="op">=-</span><span class="dv">12</span>, scale<span class="op">=</span><span class="dv">4</span>, size<span class="op">=</span><span class="dv">50</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="co"># News: Near-zero scores (balanced)</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>news_scores <span class="op">=</span> np.random.normal(loc<span class="op">=</span><span class="dv">2</span>, scale<span class="op">=</span><span class="dv">6</span>, size<span class="op">=</span><span class="dv">50</span>)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine into dataframe</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pl.DataFrame({</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">'doc_id'</span>: [<span class="ss">f'doc_</span><span class="sc">{</span>i<span class="sc">:03d}</span><span class="ss">'</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">150</span>)],</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">'genre'</span>: [<span class="st">'Fiction'</span>]<span class="op">*</span><span class="dv">50</span> <span class="op">+</span> [<span class="st">'Academic'</span>]<span class="op">*</span><span class="dv">50</span> <span class="op">+</span> [<span class="st">'News'</span>]<span class="op">*</span><span class="dv">50</span>,</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">'dimension_1'</span>: np.concatenate([fiction_scores, academic_scores, news_scores])</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Data shape: </span><span class="sc">{</span>data<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">First few rows:"</span>)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data.head())</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Genre distribution:"</span>)</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data.group_by(<span class="st">'genre'</span>).agg(pl.count()))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data shape: (150, 3)

First few rows:
shape: (5, 3)
┌─────────┬─────────┬─────────────┐
│ doc_id  ┆ genre   ┆ dimension_1 │
│ ---     ┆ ---     ┆ ---         │
│ str     ┆ str     ┆ f64         │
╞═════════╪═════════╪═════════════╡
│ doc_000 ┆ Fiction ┆ 17.483571   │
│ doc_001 ┆ Fiction ┆ 14.308678   │
│ doc_002 ┆ Fiction ┆ 18.238443   │
│ doc_003 ┆ Fiction ┆ 22.615149   │
│ doc_004 ┆ Fiction ┆ 13.829233   │
└─────────┴─────────┴─────────────┘

Genre distribution:
shape: (3, 2)
┌──────────┬───────┐
│ genre    ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ News     ┆ 50    │
│ Fiction  ┆ 50    │
│ Academic ┆ 50    │
└──────────┴───────┘</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_3079/335707288.py:31: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  print(data.group_by('genre').agg(pl.count()))</code></pre>
</div>
</div>
</section>
<section id="descriptive-statistics-by-group" class="level3" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="descriptive-statistics-by-group"><span class="header-section-number">9.4.2</span> Descriptive Statistics by Group</h3>
<div id="5b4ca047" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute group means and standard deviations</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>summary <span class="op">=</span> data.group_by(<span class="st">'genre'</span>).agg([</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    pl.col(<span class="st">'dimension_1'</span>).mean().alias(<span class="st">'mean'</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    pl.col(<span class="st">'dimension_1'</span>).std().alias(<span class="st">'std'</span>),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    pl.col(<span class="st">'dimension_1'</span>).<span class="bu">min</span>().alias(<span class="st">'min'</span>),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    pl.col(<span class="st">'dimension_1'</span>).<span class="bu">max</span>().alias(<span class="st">'max'</span>),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    pl.count().alias(<span class="st">'n'</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>]).sort(<span class="st">'mean'</span>, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Descriptive Statistics by Genre:"</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Descriptive Statistics by Genre:
shape: (3, 6)
┌──────────┬────────────┬──────────┬───────────┬───────────┬─────┐
│ genre    ┆ mean       ┆ std      ┆ min       ┆ max       ┆ n   │
│ ---      ┆ ---        ┆ ---      ┆ ---       ┆ ---       ┆ --- │
│ str      ┆ f64        ┆ f64      ┆ f64       ┆ f64       ┆ u32 │
╞══════════╪════════════╪══════════╪═══════════╪═══════════╪═════╡
│ Fiction  ┆ 13.87263   ┆ 4.668344 ┆ 5.201649  ┆ 24.261391 ┆ 50  │
│ News     ┆ 1.764275   ┆ 6.092482 ┆ -9.512627 ┆ 16.779453 ┆ 50  │
│ Academic ┆ -11.928877 ┆ 3.4973   ┆ -22.47898 ┆ -5.741425 ┆ 50  │
└──────────┴────────────┴──────────┴───────────┴───────────┴─────┘</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_3079/3474101131.py:7: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias('n')</code></pre>
</div>
</div>
<p><strong>Observation</strong>: Fiction and Academic have very different means (≈15 vs ≈-12), while News falls in between. Do these differences exceed within-group variation?</p>
</section>
<section id="visualize-group-differences" class="level3" data-number="9.4.3">
<h3 data-number="9.4.3" class="anchored" data-anchor-id="visualize-group-differences"><span class="header-section-number">9.4.3</span> Visualize Group Differences</h3>
<div id="cell-fig-anova-boxplot" class="cell" data-fig-height="6" data-fig-width="10" data-execution_count="3">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data for seaborn (dictionary format avoids pyarrow dependency)</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>plot_data <span class="op">=</span> {</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'genre'</span>: data[<span class="st">'genre'</span>].to_list(),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'dimension_1'</span>: data[<span class="st">'dimension_1'</span>].to_list()</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>sns.boxplot(data<span class="op">=</span>plot_data, x<span class="op">=</span><span class="st">'genre'</span>, y<span class="op">=</span><span class="st">'dimension_1'</span>, palette<span class="op">=</span><span class="st">'Set2'</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>sns.swarmplot(data<span class="op">=</span>plot_data, x<span class="op">=</span><span class="st">'genre'</span>, y<span class="op">=</span><span class="st">'dimension_1'</span>, color<span class="op">=</span><span class="st">'black'</span>, alpha<span class="op">=</span><span class="fl">0.3</span>, size<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Genre'</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Dimension 1: Involved vs. Informational'</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Dimension Scores by Genre'</span>, fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, label<span class="op">=</span><span class="st">'Zero line'</span>)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>plt.grid(axis<span class="op">=</span><span class="st">'y'</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_3079/131551180.py:8: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(data=plot_data, x='genre', y='dimension_1', palette='Set2')</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-anova-boxplot" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-anova-boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="categorical-variables_files/figure-html/fig-anova-boxplot-output-2.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-anova-boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: Box plots showing dimension score distributions by genre. Boxes show interquartile range, horizontal lines show medians, whiskers extend to 1.5×IQR.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Visual assessment</strong>:</p>
<ul>
<li>Do boxes (interquartile ranges) overlap substantially? (Less overlap = stronger separation)</li>
<li>Are medians far apart? (Greater distance = larger effect)</li>
<li>Is within-group variance small relative to between-group differences? (Compact boxes + large gaps = high F-statistic)</li>
</ul>
</section>
<section id="perform-one-way-anova" class="level3" data-number="9.4.4">
<h3 data-number="9.4.4" class="anchored" data-anchor-id="perform-one-way-anova"><span class="header-section-number">9.4.4</span> Perform One-Way ANOVA</h3>
<div id="9eab158a" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Separate data by group</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>fiction <span class="op">=</span> data.<span class="bu">filter</span>(pl.col(<span class="st">'genre'</span>) <span class="op">==</span> <span class="st">'Fiction'</span>).select(<span class="st">'dimension_1'</span>).to_numpy().flatten()</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>academic <span class="op">=</span> data.<span class="bu">filter</span>(pl.col(<span class="st">'genre'</span>) <span class="op">==</span> <span class="st">'Academic'</span>).select(<span class="st">'dimension_1'</span>).to_numpy().flatten()</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>news <span class="op">=</span> data.<span class="bu">filter</span>(pl.col(<span class="st">'genre'</span>) <span class="op">==</span> <span class="st">'News'</span>).select(<span class="st">'dimension_1'</span>).to_numpy().flatten()</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform one-way ANOVA</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>f_stat, p_value <span class="op">=</span> stats.f_oneway(fiction, academic, news)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">One-Way ANOVA Results:"</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  F-statistic: </span><span class="sc">{</span>f_stat<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  P-value: </span><span class="sc">{</span>p_value<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Significance: </span><span class="sc">{</span><span class="st">'***'</span> <span class="cf">if</span> p_value <span class="op">&lt;</span> <span class="fl">0.001</span> <span class="cf">else</span> <span class="st">'**'</span> <span class="cf">if</span> p_value <span class="op">&lt;</span> <span class="fl">0.01</span> <span class="cf">else</span> <span class="st">'*'</span> <span class="cf">if</span> p_value <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">'ns'</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">  Interpretation: </span><span class="sc">{</span><span class="st">'Groups differ significantly'</span> <span class="cf">if</span> p_value <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">'No significant difference'</span><span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
One-Way ANOVA Results:
  F-statistic: 351.35
  P-value: 0.000000
  Significance: ***

  Interpretation: Groups differ significantly</code></pre>
</div>
</div>
<p><strong>Interpreting p-value</strong>:</p>
<ul>
<li><strong>p &lt; 0.001</strong>: Extremely strong evidence of differences (***)</li>
<li><strong>p &lt; 0.01</strong>: Strong evidence (**)</li>
<li><strong>p &lt; 0.05</strong>: Moderate evidence (*)</li>
<li><strong>p ≥ 0.05</strong>: Insufficient evidence (ns = not significant)</li>
</ul>
<p><strong>Caution</strong>: Statistical significance ≠ practical significance. With large samples (n = 1000+), tiny differences become “significant.” Always check effect size (R²).</p>
</section>
<section id="compute-sum-of-squares-manually" class="level3" data-number="9.4.5">
<h3 data-number="9.4.5" class="anchored" data-anchor-id="compute-sum-of-squares-manually"><span class="header-section-number">9.4.5</span> Compute Sum of Squares Manually</h3>
<div id="a25be5d1" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract all scores and compute grand mean</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>all_scores <span class="op">=</span> data.select(<span class="st">'dimension_1'</span>).to_numpy().flatten()</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>grand_mean <span class="op">=</span> np.mean(all_scores)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Grand mean: </span><span class="sc">{</span>grand_mean<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># SS_total: Total sum of squares</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>ss_total <span class="op">=</span> np.<span class="bu">sum</span>((all_scores <span class="op">-</span> grand_mean)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"SS_total: </span><span class="sc">{</span>ss_total<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co"># SS_between: Between-group sum of squares</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>n_fiction <span class="op">=</span> <span class="bu">len</span>(fiction)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>n_academic <span class="op">=</span> <span class="bu">len</span>(academic)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>n_news <span class="op">=</span> <span class="bu">len</span>(news)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>mean_fiction <span class="op">=</span> np.mean(fiction)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>mean_academic <span class="op">=</span> np.mean(academic)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>mean_news <span class="op">=</span> np.mean(news)</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>ss_between <span class="op">=</span> (n_fiction <span class="op">*</span> (mean_fiction <span class="op">-</span> grand_mean)<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> </span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>              n_academic <span class="op">*</span> (mean_academic <span class="op">-</span> grand_mean)<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> </span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>              n_news <span class="op">*</span> (mean_news <span class="op">-</span> grand_mean)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"SS_between: </span><span class="sc">{</span>ss_between<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a><span class="co"># SS_within: Within-group sum of squares</span></span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>ss_within_fiction <span class="op">=</span> np.<span class="bu">sum</span>((fiction <span class="op">-</span> mean_fiction)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>ss_within_academic <span class="op">=</span> np.<span class="bu">sum</span>((academic <span class="op">-</span> mean_academic)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>ss_within_news <span class="op">=</span> np.<span class="bu">sum</span>((news <span class="op">-</span> mean_news)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>ss_within <span class="op">=</span> ss_within_fiction <span class="op">+</span> ss_within_academic <span class="op">+</span> ss_within_news</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"SS_within: </span><span class="sc">{</span>ss_within<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Check: SS_total should equal SS_between + SS_within</span></span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Check: SS_between + SS_within = </span><span class="sc">{</span>ss_between <span class="op">+</span> ss_within<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"       (should equal SS_total = </span><span class="sc">{</span>ss_total<span class="sc">:.2f}</span><span class="ss">)"</span>)</span>
<span id="cb16-37"><a href="#cb16-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"       Difference: </span><span class="sc">{</span><span class="bu">abs</span>(ss_total <span class="op">-</span> (ss_between <span class="op">+</span> ss_within))<span class="sc">:.6f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Grand mean: 1.24
SS_total: 20149.87
SS_between: 16663.87
SS_within: 3486.00

Check: SS_between + SS_within = 20149.87
       (should equal SS_total = 20149.87)
       Difference: 0.000000</code></pre>
</div>
</div>
<p><strong>Observation</strong>: The components should sum exactly (or within tiny rounding error). This confirms variance partitioning is correct.</p>
</section>
<section id="compute-r²-η²" class="level3" data-number="9.4.6">
<h3 data-number="9.4.6" class="anchored" data-anchor-id="compute-r²-η²"><span class="header-section-number">9.4.6</span> Compute R² (η²)</h3>
<div id="1f2b9ace" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Eta-squared: Proportion of variance explained</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>eta_squared <span class="op">=</span> ss_between <span class="op">/</span> ss_total</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Effect Size:"</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  η² (eta-squared): </span><span class="sc">{</span>eta_squared<span class="sc">:.4f}</span><span class="ss"> (</span><span class="sc">{</span>eta_squared<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%)"</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Interpret effect size</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> eta_squared <span class="op">&gt;=</span> <span class="fl">0.14</span>:</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    effect <span class="op">=</span> <span class="st">"Large (η² ≥ 0.14)"</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="cf">elif</span> eta_squared <span class="op">&gt;=</span> <span class="fl">0.06</span>:</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    effect <span class="op">=</span> <span class="st">"Medium (0.06 ≤ η² &lt; 0.14)"</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="cf">elif</span> eta_squared <span class="op">&gt;=</span> <span class="fl">0.01</span>:</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    effect <span class="op">=</span> <span class="st">"Small (0.01 ≤ η² &lt; 0.06)"</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    effect <span class="op">=</span> <span class="st">"Negligible (η² &lt; 0.01)"</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Interpretation: </span><span class="sc">{</span>effect<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">  Meaning: Genre explains </span><span class="sc">{</span>eta_squared<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">% of variance in dimension scores."</span>)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"           Remaining </span><span class="sc">{</span>(<span class="dv">1</span><span class="op">-</span>eta_squared)<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">% is individual variation within genres."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Effect Size:
  η² (eta-squared): 0.8270 (82.70%)
  Interpretation: Large (η² ≥ 0.14)

  Meaning: Genre explains 82.7% of variance in dimension scores.
           Remaining 17.3% is individual variation within genres.</code></pre>
</div>
</div>
<p><strong>In text analysis</strong>: η² = 0.50 means dimension is a strong genre marker (genre explains half the variation). η² = 0.10 means weak marker (only 10% explained).</p>
</section>
<section id="compute-f-statistic-manually" class="level3" data-number="9.4.7">
<h3 data-number="9.4.7" class="anchored" data-anchor-id="compute-f-statistic-manually"><span class="header-section-number">9.4.7</span> Compute F-Statistic Manually</h3>
<div id="90f3f986" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Degrees of freedom</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="dv">3</span>  <span class="co"># Number of groups</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(all_scores)  <span class="co"># Total observations</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>df_between <span class="op">=</span> k <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>df_within <span class="op">=</span> n <span class="op">-</span> k</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Degrees of Freedom:"</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Between groups (df_between): </span><span class="sc">{</span>df_between<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Within groups (df_within): </span><span class="sc">{</span>df_within<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean squares</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>ms_between <span class="op">=</span> ss_between <span class="op">/</span> df_between</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>ms_within <span class="op">=</span> ss_within <span class="op">/</span> df_within</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Mean Squares:"</span>)</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  MS_between: </span><span class="sc">{</span>ms_between<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  MS_within: </span><span class="sc">{</span>ms_within<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a><span class="co"># F-statistic</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>f_statistic <span class="op">=</span> ms_between <span class="op">/</span> ms_within</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">F-Statistic:"</span>)</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  F = </span><span class="sc">{</span>f_statistic<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  (Should match scipy.stats.f_oneway result: </span><span class="sc">{</span>f_stat<span class="sc">:.2f}</span><span class="ss">)"</span>)</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a><span class="co"># P-value from F-distribution</span></span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>p_value_manual <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> stats.f.cdf(f_statistic, df_between, df_within)</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  P-value: </span><span class="sc">{</span>p_value_manual<span class="sc">:.6f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Degrees of Freedom:
  Between groups (df_between): 2
  Within groups (df_within): 147

Mean Squares:
  MS_between: 8331.94
  MS_within: 23.71

F-Statistic:
  F = 351.35
  (Should match scipy.stats.f_oneway result: 351.35)
  P-value: 0.000000</code></pre>
</div>
</div>
<p><strong>Understanding F</strong>:</p>
<ul>
<li><strong>F = MS_between / MS_within</strong>: Ratio of between-group to within-group variance</li>
<li><strong>Large F</strong> (e.g., F &gt; 10): Between-group variance much larger than within-group</li>
<li><strong>F ≈ 1</strong>: Between-group and within-group variance similar (no group effect)</li>
</ul>
</section>
<section id="anova-table" class="level3" data-number="9.4.8">
<h3 data-number="9.4.8" class="anchored" data-anchor-id="anova-table"><span class="header-section-number">9.4.8</span> ANOVA Table</h3>
<div id="c5cbfa82" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create standard ANOVA table</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>anova_table <span class="op">=</span> pd.DataFrame({</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Source'</span>: [<span class="st">'Between Groups'</span>, <span class="st">'Within Groups'</span>, <span class="st">'Total'</span>],</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'SS'</span>: [ss_between, ss_within, ss_total],</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'df'</span>: [df_between, df_within, n<span class="op">-</span><span class="dv">1</span>],</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'MS'</span>: [ms_between, ms_within, np.nan],</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'F'</span>: [f_statistic, np.nan, np.nan],</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'P-value'</span>: [p_value_manual, np.nan, np.nan]</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">ANOVA Table:"</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(anova_table.to_string(index<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ANOVA Table:
        Source           SS  df          MS          F  P-value
Between Groups 16663.873876   2 8331.936938 351.346661      0.0
 Within Groups  3486.000769 147   23.714291        NaN      NaN
         Total 20149.874645 149         NaN        NaN      NaN</code></pre>
</div>
</div>
<p><strong>Reading ANOVA table</strong>:</p>
<ul>
<li><strong>SS column</strong>: Variance components (between + within = total)</li>
<li><strong>df column</strong>: Degrees of freedom for each component</li>
<li><strong>MS column</strong>: Mean squares (SS / df) = variance estimates</li>
<li><strong>F column</strong>: Test statistic (MS_between / MS_within)</li>
<li><strong>P-value</strong>: Significance test result</li>
</ul>
<p>This is the standard format for reporting ANOVA results in publications.</p>
</section>
</section>
<section id="post-hoc-tests-which-groups-differ" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="post-hoc-tests-which-groups-differ"><span class="header-section-number">9.5</span> Post-Hoc Tests: Which Groups Differ?</h2>
<p>ANOVA tells us groups differ overall, but <strong>which specific pairs</strong> differ?</p>
<section id="the-multiple-comparisons-problem" class="level3" data-number="9.5.1">
<h3 data-number="9.5.1" class="anchored" data-anchor-id="the-multiple-comparisons-problem"><span class="header-section-number">9.5.1</span> The Multiple Comparisons Problem</h3>
<p>With 3 genres, there are 3 pairwise comparisons:</p>
<ol type="1">
<li>Fiction vs.&nbsp;Academic</li>
<li>Fiction vs.&nbsp;News<br>
</li>
<li>Academic vs.&nbsp;News</li>
</ol>
<p>Testing each with separate t-tests inflates Type I error (false positives). If each test has α = 0.05, probability of at least one false positive:</p>
<p><span class="math display">\[P(Type\text{ }I\text{ }error) = 1 - (1 - 0.05)^3 = 0.143\]</span></p>
<p>With 15 genres (105 pairwise comparisons), this rises to 99.5% chance of false positive!</p>
<p><strong>Solution</strong>: Post-hoc tests adjust for multiple comparisons.</p>
</section>
<section id="tukeys-hsd-honestly-significant-difference" class="level3" data-number="9.5.2">
<h3 data-number="9.5.2" class="anchored" data-anchor-id="tukeys-hsd-honestly-significant-difference"><span class="header-section-number">9.5.2</span> Tukey’s HSD (Honestly Significant Difference)</h3>
<p><strong>Most common post-hoc test</strong>:</p>
<ul>
<li>Controls family-wise error rate (overall α = 0.05)</li>
<li>More conservative than unadjusted t-tests</li>
<li>Good balance between power and protection</li>
</ul>
<div id="831b648a" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.multicomp <span class="im">import</span> pairwise_tukeyhsd</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Tukey HSD</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>tukey <span class="op">=</span> pairwise_tukeyhsd(endog<span class="op">=</span>data[<span class="st">'dimension_1'</span>].to_numpy(), groups<span class="op">=</span>data[<span class="st">'genre'</span>].to_numpy(), alpha<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Tukey HSD Post-Hoc Test:"</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tukey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Tukey HSD Post-Hoc Test:
  Multiple Comparison of Means - Tukey HSD, FWER=0.05  
=======================================================
 group1   group2 meandiff p-adj  lower    upper  reject
-------------------------------------------------------
Academic Fiction  25.8015   0.0  23.4955 28.1075   True
Academic    News  13.6932   0.0  11.3871 15.9992   True
 Fiction    News -12.1084   0.0 -14.4144 -9.8023   True
-------------------------------------------------------</code></pre>
</div>
</div>
<p><strong>Reading Tukey output</strong>:</p>
<ul>
<li><strong>meandiff</strong>: Difference between group means</li>
<li><strong>lower/upper</strong>: 95% confidence interval for difference</li>
<li><strong>reject</strong>: True if difference is significant (p &lt; 0.05)</li>
</ul>
<p><strong>Example interpretation</strong>:</p>
<pre><code>group1    group2     meandiff  lower   upper   reject
Academic  Fiction    -27.3     -29.1   -25.5   True
Academic  News       -14.2     -16.0   -12.4   True  
Fiction   News       13.1      11.3    14.9    True</code></pre>
<p>All three pairs differ significantly. Fiction scores highest (+15), News middle (+2), Academic lowest (-12).</p>
</section>
<section id="visualize-post-hoc-results" class="level3" data-number="9.5.3">
<h3 data-number="9.5.3" class="anchored" data-anchor-id="visualize-post-hoc-results"><span class="header-section-number">9.5.3</span> Visualize Post-Hoc Results</h3>
<div id="cell-fig-tukey-intervals" class="cell" data-fig-height="6" data-fig-width="10" data-execution_count="10">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute means and confidence intervals</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>genre_means <span class="op">=</span> summary.sort(<span class="st">'mean'</span>, descending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># For 95% CI: mean ± (critical_value × SE)</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># SE = std / sqrt(n)</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="co"># critical_value ≈ 1.96 for large samples</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>genre_means <span class="op">=</span> genre_means.with_columns([</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    (pl.col(<span class="st">'std'</span>) <span class="op">/</span> pl.col(<span class="st">'n'</span>).sqrt()).alias(<span class="st">'se'</span>),</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    (pl.col(<span class="st">'mean'</span>) <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> pl.col(<span class="st">'std'</span>) <span class="op">/</span> pl.col(<span class="st">'n'</span>).sqrt()).alias(<span class="st">'ci_lower'</span>),</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    (pl.col(<span class="st">'mean'</span>) <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> pl.col(<span class="st">'std'</span>) <span class="op">/</span> pl.col(<span class="st">'n'</span>).sqrt()).alias(<span class="st">'ci_upper'</span>)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract values from Polars DataFrame using to_list()</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>genres_list <span class="op">=</span> genre_means[<span class="st">'genre'</span>].to_list()</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>means_list <span class="op">=</span> genre_means[<span class="st">'mean'</span>].to_list()</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>ci_lower_list <span class="op">=</span> genre_means[<span class="st">'ci_lower'</span>].to_list()</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>ci_upper_list <span class="op">=</span> genre_means[<span class="st">'ci_upper'</span>].to_list()</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>plt.errorbar(</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="bu">range</span>(<span class="bu">len</span>(genres_list)),</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>means_list,</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>    yerr<span class="op">=</span>[[means_list[i] <span class="op">-</span> ci_lower_list[i] <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(means_list))],</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>          [ci_upper_list[i] <span class="op">-</span> means_list[i] <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(means_list))]],</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>    fmt<span class="op">=</span><span class="st">'o'</span>,</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>    markersize<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>    capsize<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>    capthick<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>    linewidth<span class="op">=</span><span class="dv">2</span></span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a>plt.xticks(<span class="bu">range</span>(<span class="bu">len</span>(genres_list)), genres_list, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Mean Dimension 1 Score'</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Genre'</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Genre Means with 95% Confidence Intervals'</span>, fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb27-36"><a href="#cb27-36" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, label<span class="op">=</span><span class="st">'Zero line'</span>)</span>
<span id="cb27-37"><a href="#cb27-37" aria-hidden="true" tabindex="-1"></a>plt.grid(axis<span class="op">=</span><span class="st">'y'</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb27-38"><a href="#cb27-38" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb27-39"><a href="#cb27-39" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb27-40"><a href="#cb27-40" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-tukey-intervals" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tukey-intervals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="categorical-variables_files/figure-html/fig-tukey-intervals-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tukey-intervals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.2: Mean dimension scores by genre with 95% confidence intervals. Non-overlapping intervals indicate significant differences (Tukey-adjusted).
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong>: Non-overlapping error bars suggest significant differences (though this is approximate—Tukey is more conservative).</p>
</section>
<section id="bonferroni-correction-alternative" class="level3" data-number="9.5.4">
<h3 data-number="9.5.4" class="anchored" data-anchor-id="bonferroni-correction-alternative"><span class="header-section-number">9.5.4</span> Bonferroni Correction (Alternative)</h3>
<p><strong>More conservative than Tukey</strong>:</p>
<ul>
<li>Divide α by number of comparisons: α_adjusted = 0.05 / 3 = 0.0167</li>
<li>Reject H₀ only if p &lt; 0.0167</li>
</ul>
<p><strong>When to use</strong>:</p>
<ul>
<li>Planned comparisons (you know which pairs to test before analysis)</li>
<li>Fewer comparisons (3-5 pairs)</li>
</ul>
<p><strong>When not to use</strong>:</p>
<ul>
<li>Exploratory analysis (many unplanned comparisons)</li>
<li>Risk of Type II error (false negatives) increases</li>
</ul>
<div id="e4d2632b" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bonferroni-corrected pairwise t-tests</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>comparisons <span class="op">=</span> [</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'Fiction'</span>, <span class="st">'Academic'</span>),</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'Fiction'</span>, <span class="st">'News'</span>),</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'Academic'</span>, <span class="st">'News'</span>)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>n_comparisons <span class="op">=</span> <span class="bu">len</span>(comparisons)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>alpha_bonferroni <span class="op">=</span> <span class="fl">0.05</span> <span class="op">/</span> n_comparisons</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Bonferroni Correction:"</span>)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Number of comparisons: </span><span class="sc">{</span>n_comparisons<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Adjusted α: </span><span class="sc">{</span>alpha_bonferroni<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Pairwise t-tests:"</span>)</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> group1, group2 <span class="kw">in</span> comparisons:</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>    data1 <span class="op">=</span> data.<span class="bu">filter</span>(pl.col(<span class="st">'genre'</span>) <span class="op">==</span> group1).select(<span class="st">'dimension_1'</span>).to_numpy().flatten()</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>    data2 <span class="op">=</span> data.<span class="bu">filter</span>(pl.col(<span class="st">'genre'</span>) <span class="op">==</span> group2).select(<span class="st">'dimension_1'</span>).to_numpy().flatten()</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>    t_stat, p_val <span class="op">=</span> ttest_ind(data1, data2)</span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>    sig <span class="op">=</span> <span class="st">"***"</span> <span class="cf">if</span> p_val <span class="op">&lt;</span> <span class="fl">0.001</span> <span class="cf">else</span> <span class="st">"**"</span> <span class="cf">if</span> p_val <span class="op">&lt;</span> <span class="fl">0.01</span> <span class="cf">else</span> <span class="st">"*"</span> <span class="cf">if</span> p_val <span class="op">&lt;</span> alpha_bonferroni <span class="cf">else</span> <span class="st">"ns"</span></span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>group1<span class="sc">}</span><span class="ss"> vs </span><span class="sc">{</span>group2<span class="sc">}</span><span class="ss">:"</span>)</span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"    t = </span><span class="sc">{</span>t_stat<span class="sc">:.2f}</span><span class="ss">, p = </span><span class="sc">{</span>p_val<span class="sc">:.6f}</span><span class="ss"> </span><span class="sc">{</span>sig<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"    Mean diff: </span><span class="sc">{</span>np<span class="sc">.</span>mean(data1) <span class="op">-</span> np<span class="sc">.</span>mean(data2)<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Bonferroni Correction:
  Number of comparisons: 3
  Adjusted α: 0.0167

Pairwise t-tests:
  Fiction vs Academic:
    t = 31.28, p = 0.000000 ***
    Mean diff: 25.80
  Fiction vs News:
    t = 11.15, p = 0.000000 ***
    Mean diff: 12.11
  Academic vs News:
    t = -13.78, p = 0.000000 ***
    Mean diff: -13.69</code></pre>
</div>
</div>
</section>
</section>
<section id="anova-in-mda-example" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="anova-in-mda-example"><span class="header-section-number">9.6</span> ANOVA in MDA: Example</h2>
<p>After extracting dimensions with Factor Analysis or PCA, we test if they distinguish genres:</p>
<section id="load-mda-results" class="level3" data-number="9.6.1">
<h3 data-number="9.6.1" class="anchored" data-anchor-id="load-mda-results"><span class="header-section-number">9.6.1</span> Load MDA Results</h3>
<div id="8e357e28" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assume we've run MDA on Brown Corpus and extracted dimension scores</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># In practice, this would come from pybiber:</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="co"># df = pb.BiberAnalyzer(dfm_biber, id_column=True)</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># df.mda(n_factors=3)</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="co"># dimension_scores = df.mda_scores  # DataFrame with dimension scores</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># For this tutorial, simulate realistic MDA dimension scores</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">123</span>)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>genres <span class="op">=</span> [<span class="st">'Fiction'</span>, <span class="st">'Academic'</span>, <span class="st">'News'</span>, <span class="st">'Government'</span>, <span class="st">'Humor'</span>] <span class="op">*</span> <span class="dv">30</span>  <span class="co"># 150 texts</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>n_texts <span class="op">=</span> <span class="bu">len</span>(genres)</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Dimension 1: Involved vs. Informational (Fiction high, Academic low)</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>dim1_base <span class="op">=</span> {<span class="st">'Fiction'</span>: <span class="dv">18</span>, <span class="st">'Academic'</span>: <span class="op">-</span><span class="dv">15</span>, <span class="st">'News'</span>: <span class="dv">3</span>, <span class="st">'Government'</span>: <span class="op">-</span><span class="dv">8</span>, <span class="st">'Humor'</span>: <span class="dv">12</span>}</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>dim1_scores <span class="op">=</span> [np.random.normal(dim1_base[g], <span class="dv">6</span>) <span class="cf">for</span> g <span class="kw">in</span> genres]</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Dimension 2: Narrative vs. Non-narrative (Fiction high)</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>dim2_base <span class="op">=</span> {<span class="st">'Fiction'</span>: <span class="dv">14</span>, <span class="st">'Academic'</span>: <span class="op">-</span><span class="dv">5</span>, <span class="st">'News'</span>: <span class="dv">4</span>, <span class="st">'Government'</span>: <span class="op">-</span><span class="dv">3</span>, <span class="st">'Humor'</span>: <span class="dv">8</span>}</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>dim2_scores <span class="op">=</span> [np.random.normal(dim2_base[g], <span class="dv">5</span>) <span class="cf">for</span> g <span class="kw">in</span> genres]</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Dimension 3: Abstract vs. Concrete (Academic high)</span></span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>dim3_base <span class="op">=</span> {<span class="st">'Fiction'</span>: <span class="op">-</span><span class="dv">2</span>, <span class="st">'Academic'</span>: <span class="dv">12</span>, <span class="st">'News'</span>: <span class="dv">1</span>, <span class="st">'Government'</span>: <span class="dv">6</span>, <span class="st">'Humor'</span>: <span class="op">-</span><span class="dv">4</span>}</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>dim3_scores <span class="op">=</span> [np.random.normal(dim3_base[g], <span class="dv">4</span>) <span class="cf">for</span> g <span class="kw">in</span> genres]</span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>mda_data <span class="op">=</span> pl.DataFrame({</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">'doc_id'</span>: [<span class="ss">f'text_</span><span class="sc">{</span>i<span class="sc">:03d}</span><span class="ss">'</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_texts)],</span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">'genre'</span>: genres,</span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">'dimension_1'</span>: dim1_scores,</span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">'dimension_2'</span>: dim2_scores,</span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a>    <span class="st">'dimension_3'</span>: dim3_scores</span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"MDA Dimension Scores:"</span>)</span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(mda_data.head(<span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>MDA Dimension Scores:
shape: (10, 5)
┌──────────┬────────────┬─────────────┬─────────────┬─────────────┐
│ doc_id   ┆ genre      ┆ dimension_1 ┆ dimension_2 ┆ dimension_3 │
│ ---      ┆ ---        ┆ ---         ┆ ---         ┆ ---         │
│ str      ┆ str        ┆ f64         ┆ f64         ┆ f64         │
╞══════════╪════════════╪═════════════╪═════════════╪═════════════╡
│ text_000 ┆ Fiction    ┆ 11.486216   ┆ 15.269082   ┆ 1.060219    │
│ text_001 ┆ Academic   ┆ -9.015927   ┆ -3.581373   ┆ 8.684045    │
│ text_002 ┆ News       ┆ 4.697871    ┆ -3.059444   ┆ -1.636605   │
│ text_003 ┆ Government ┆ -17.037768  ┆ -12.384343  ┆ 8.444494    │
│ text_004 ┆ Humor      ┆ 8.528398    ┆ 2.901725    ┆ -4.576053   │
│ text_005 ┆ Fiction    ┆ 27.908619   ┆ 14.839711   ┆ 3.266422    │
│ text_006 ┆ Academic   ┆ -29.560075  ┆ -2.230719   ┆ 9.182631    │
│ text_007 ┆ News       ┆ 0.426524    ┆ 1.346627    ┆ 4.00244     │
│ text_008 ┆ Government ┆ -0.404382   ┆ 3.886287    ┆ 7.370552    │
│ text_009 ┆ Humor      ┆ 6.799558    ┆ 7.28412     ┆ -4.50575    │
└──────────┴────────────┴─────────────┴─────────────┴─────────────┘</code></pre>
</div>
</div>
</section>
<section id="test-each-dimension" class="level3" data-number="9.6.2">
<h3 data-number="9.6.2" class="anchored" data-anchor-id="test-each-dimension"><span class="header-section-number">9.6.2</span> Test Each Dimension</h3>
<div id="7558cb6d" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Separate by genre using Polars and convert to numpy</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>genre_groups <span class="op">=</span> {</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    genre: mda_data.<span class="bu">filter</span>(pl.col(<span class="st">'genre'</span>) <span class="op">==</span> genre)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> genre <span class="kw">in</span> [<span class="st">'Fiction'</span>, <span class="st">'Academic'</span>, <span class="st">'News'</span>, <span class="st">'Government'</span>, <span class="st">'Humor'</span>]</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Test each dimension</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> dim <span class="kw">in</span> [<span class="st">'dimension_1'</span>, <span class="st">'dimension_2'</span>, <span class="st">'dimension_3'</span>]:</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span><span class="st">'='</span><span class="op">*</span><span class="dv">60</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"ANOVA for </span><span class="sc">{</span>dim<span class="sc">.</span>replace(<span class="st">'_'</span>, <span class="st">' '</span>)<span class="sc">.</span>title()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'='</span><span class="op">*</span><span class="dv">60</span>)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Extract dimension scores by genre (convert to numpy arrays)</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>    groups <span class="op">=</span> [genre_groups[g][dim].to_numpy() <span class="cf">for</span> g <span class="kw">in</span> [<span class="st">'Fiction'</span>, <span class="st">'Academic'</span>, <span class="st">'News'</span>, <span class="st">'Government'</span>, <span class="st">'Humor'</span>]]</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># One-way ANOVA</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>    f_stat, p_val <span class="op">=</span> stats.f_oneway(<span class="op">*</span>groups)</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute eta-squared</span></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>    all_scores <span class="op">=</span> mda_data.select(dim).to_numpy().flatten()</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>    grand_mean <span class="op">=</span> np.mean(all_scores)</span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>    ss_total <span class="op">=</span> np.<span class="bu">sum</span>((all_scores <span class="op">-</span> grand_mean)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>    ss_between <span class="op">=</span> <span class="bu">sum</span>([</span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>        <span class="bu">len</span>(group) <span class="op">*</span> (np.mean(group) <span class="op">-</span> grand_mean)<span class="op">**</span><span class="dv">2</span> </span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> group <span class="kw">in</span> groups</span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a>    eta_sq <span class="op">=</span> ss_between <span class="op">/</span> ss_total</span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Report</span></span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  F(</span><span class="sc">{</span><span class="dv">4</span><span class="sc">}</span><span class="ss">, </span><span class="sc">{</span>n_texts<span class="op">-</span><span class="dv">5</span><span class="sc">}</span><span class="ss">) = </span><span class="sc">{</span>f_stat<span class="sc">:.2f}</span><span class="ss">, p = </span><span class="sc">{</span>p_val<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  η² = </span><span class="sc">{</span>eta_sq<span class="sc">:.3f}</span><span class="ss"> (</span><span class="sc">{</span>eta_sq<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">% variance explained)"</span>)</span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> eta_sq <span class="op">&gt;=</span> <span class="fl">0.14</span>:</span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a>        effect <span class="op">=</span> <span class="st">"Large"</span></span>
<span id="cb32-37"><a href="#cb32-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> eta_sq <span class="op">&gt;=</span> <span class="fl">0.06</span>:</span>
<span id="cb32-38"><a href="#cb32-38" aria-hidden="true" tabindex="-1"></a>        effect <span class="op">=</span> <span class="st">"Medium"</span></span>
<span id="cb32-39"><a href="#cb32-39" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> eta_sq <span class="op">&gt;=</span> <span class="fl">0.01</span>:</span>
<span id="cb32-40"><a href="#cb32-40" aria-hidden="true" tabindex="-1"></a>        effect <span class="op">=</span> <span class="st">"Small"</span></span>
<span id="cb32-41"><a href="#cb32-41" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb32-42"><a href="#cb32-42" aria-hidden="true" tabindex="-1"></a>        effect <span class="op">=</span> <span class="st">"Negligible"</span></span>
<span id="cb32-43"><a href="#cb32-43" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-44"><a href="#cb32-44" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  Effect size: </span><span class="sc">{</span>effect<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb32-45"><a href="#cb32-45" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-46"><a href="#cb32-46" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Interpretation</span></span>
<span id="cb32-47"><a href="#cb32-47" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> p_val <span class="op">&lt;</span> <span class="fl">0.001</span>:</span>
<span id="cb32-48"><a href="#cb32-48" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"  *** Dimension strongly distinguishes genres (p &lt; 0.001)"</span>)</span>
<span id="cb32-49"><a href="#cb32-49" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> p_val <span class="op">&lt;</span> <span class="fl">0.05</span>:</span>
<span id="cb32-50"><a href="#cb32-50" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"  * Dimension distinguishes genres (p &lt; 0.05)"</span>)</span>
<span id="cb32-51"><a href="#cb32-51" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb32-52"><a href="#cb32-52" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"  Dimension does not distinguish genres (p ≥ 0.05)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
============================================================
ANOVA for Dimension 1
============================================================
  F(4, 145) = 130.99, p = 0.000000
  η² = 0.783 (78.3% variance explained)
  Effect size: Large
  *** Dimension strongly distinguishes genres (p &lt; 0.001)

============================================================
ANOVA for Dimension 2
============================================================
  F(4, 145) = 77.39, p = 0.000000
  η² = 0.681 (68.1% variance explained)
  Effect size: Large
  *** Dimension strongly distinguishes genres (p &lt; 0.001)

============================================================
ANOVA for Dimension 3
============================================================
  F(4, 145) = 88.82, p = 0.000000
  η² = 0.710 (71.0% variance explained)
  Effect size: Large
  *** Dimension strongly distinguishes genres (p &lt; 0.001)</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>:</p>
<ul>
<li><strong>High η²</strong> (&gt; 0.14): Dimension is strong genre marker (use for classification)</li>
<li><strong>Moderate η²</strong> (0.06-0.14): Dimension shows genre patterns (interesting for interpretation)</li>
<li><strong>Low η²</strong> (&lt; 0.06): Dimension captures variation within genres (individual differences, not genre)</li>
</ul>
<p><strong>In MDA publications</strong>, report η² for each dimension to show which dimensions best distinguish categories.</p>
</section>
<section id="visualize-dimension-performance" class="level3" data-number="9.6.3">
<h3 data-number="9.6.3" class="anchored" data-anchor-id="visualize-dimension-performance"><span class="header-section-number">9.6.3</span> Visualize Dimension Performance</h3>
<div id="cell-fig-dimension-eta-squared" class="cell" data-fig-height="6" data-fig-width="10" data-execution_count="14">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute eta-squared for all dimensions</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>eta_squared_results <span class="op">=</span> []</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> dim <span class="kw">in</span> [<span class="st">'dimension_1'</span>, <span class="st">'dimension_2'</span>, <span class="st">'dimension_3'</span>]:</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    all_scores <span class="op">=</span> mda_data.select(dim).to_numpy().flatten()</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    grand_mean <span class="op">=</span> np.mean(all_scores)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    ss_total <span class="op">=</span> np.<span class="bu">sum</span>((all_scores <span class="op">-</span> grand_mean)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    groups <span class="op">=</span> [genre_groups[g][dim].to_numpy() <span class="cf">for</span> g <span class="kw">in</span> [<span class="st">'Fiction'</span>, <span class="st">'Academic'</span>, <span class="st">'News'</span>, <span class="st">'Government'</span>, <span class="st">'Humor'</span>]]</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>    ss_between <span class="op">=</span> <span class="bu">sum</span>([<span class="bu">len</span>(group) <span class="op">*</span> (np.mean(group) <span class="op">-</span> grand_mean)<span class="op">**</span><span class="dv">2</span> <span class="cf">for</span> group <span class="kw">in</span> groups])</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>    eta_sq <span class="op">=</span> ss_between <span class="op">/</span> ss_total</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>    eta_squared_results.append({<span class="st">'Dimension'</span>: dim.replace(<span class="st">'_'</span>, <span class="st">' '</span>).title(), <span class="st">'Eta_Squared'</span>: eta_sq})</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>eta_df <span class="op">=</span> pd.DataFrame(eta_squared_results)</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> plt.bar(eta_df[<span class="st">'Dimension'</span>], eta_df[<span class="st">'Eta_Squared'</span>], color<span class="op">=</span>[<span class="st">'#1f77b4'</span>, <span class="st">'#ff7f0e'</span>, <span class="st">'#2ca02c'</span>], alpha<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Add effect size threshold lines</span></span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="fl">0.14</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, label<span class="op">=</span><span class="st">'Large effect (η² = 0.14)'</span>)</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="fl">0.06</span>, color<span class="op">=</span><span class="st">'orange'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, label<span class="op">=</span><span class="st">'Medium effect (η² = 0.06)'</span>)</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="fl">0.01</span>, color<span class="op">=</span><span class="st">'yellow'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, label<span class="op">=</span><span class="st">'Small effect (η² = 0.01)'</span>)</span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Add value labels on bars</span></span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> bar <span class="kw">in</span> bars:</span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a>    height <span class="op">=</span> bar.get_height()</span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a>    plt.text(bar.get_x() <span class="op">+</span> bar.get_width()<span class="op">/</span><span class="fl">2.</span>, height <span class="op">+</span> <span class="fl">0.01</span>,</span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a>             <span class="ss">f'</span><span class="sc">{</span>height<span class="sc">:.3f}</span><span class="ch">\n</span><span class="ss">(</span><span class="sc">{</span>height<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%)'</span>,</span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a>             ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'bottom'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Eta-Squared (η²)'</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Dimension'</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Proportion of Variance Explained by Genre Membership'</span>, fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a>plt.ylim(<span class="dv">0</span>, <span class="bu">max</span>(eta_df[<span class="st">'Eta_Squared'</span>]) <span class="op">*</span> <span class="fl">1.2</span>)</span>
<span id="cb34-36"><a href="#cb34-36" aria-hidden="true" tabindex="-1"></a>plt.legend(fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb34-37"><a href="#cb34-37" aria-hidden="true" tabindex="-1"></a>plt.grid(axis<span class="op">=</span><span class="st">'y'</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb34-38"><a href="#cb34-38" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb34-39"><a href="#cb34-39" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-dimension-eta-squared" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dimension-eta-squared-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="categorical-variables_files/figure-html/fig-dimension-eta-squared-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dimension-eta-squared-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.3: Variance explained (η²) by each dimension. Higher values indicate stronger genre differentiation.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Decision guide</strong>:</p>
<ul>
<li>Dimensions with η² &gt; 0.14 are strong genre markers (feature in main analysis)</li>
<li>Dimensions with η² &lt; 0.06 may capture stylistic variation orthogonal to genre (secondary interest)</li>
</ul>
</section>
</section>
<section id="assumptions-and-diagnostics" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="assumptions-and-diagnostics"><span class="header-section-number">9.7</span> Assumptions and Diagnostics</h2>
<p>ANOVA makes assumptions that should be checked:</p>
<section id="independence" class="level3" data-number="9.7.1">
<h3 data-number="9.7.1" class="anchored" data-anchor-id="independence"><span class="header-section-number">9.7.1</span> 1. Independence</h3>
<p><strong>Assumption</strong>: Observations are independent (one text’s score doesn’t affect another’s).</p>
<p><strong>Violation</strong>: Clustered data (multiple texts by same author, same time period).</p>
<p><strong>Check</strong>: Know your data structure. If texts are nested (authors within genres), use <strong>nested ANOVA</strong> or <strong>mixed-effects models</strong>.</p>
<p><strong>In text analysis</strong>: Usually okay if texts are from different sources. Problematic if entire corpus is one author’s works.</p>
</section>
<section id="normality" class="level3" data-number="9.7.2">
<h3 data-number="9.7.2" class="anchored" data-anchor-id="normality"><span class="header-section-number">9.7.2</span> 2. Normality</h3>
<p><strong>Assumption</strong>: Dimension scores are approximately normally distributed within each group.</p>
<p><strong>Violation</strong>: Severely skewed or bimodal distributions.</p>
<p><strong>Check</strong>: Histogram or Q-Q plot for each group.</p>
<p><strong>Robustness</strong>: ANOVA is fairly robust to non-normality with moderate sample sizes (n &gt; 30 per group).</p>
<p><strong>Alternative</strong>: If severely violated, use <strong>Kruskal-Wallis test</strong> (non-parametric ANOVA).</p>
<div id="26559d5d" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check normality for each group (Dimension 1)</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> shapiro</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Normality Tests (Shapiro-Wilk):"</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> genre <span class="kw">in</span> [<span class="st">'Fiction'</span>, <span class="st">'Academic'</span>, <span class="st">'News'</span>]:</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    genre_data <span class="op">=</span> data.<span class="bu">filter</span>(pl.col(<span class="st">'genre'</span>) <span class="op">==</span> genre).select(<span class="st">'dimension_1'</span>).to_numpy().flatten()</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    stat, p <span class="op">=</span> shapiro(genre_data)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>genre<span class="sc">}</span><span class="ss">: W = </span><span class="sc">{</span>stat<span class="sc">:.4f}</span><span class="ss">, p = </span><span class="sc">{</span>p<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> p <span class="op">&lt;</span> <span class="fl">0.05</span>:</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"    → Non-normal distribution (p &lt; 0.05)"</span>)</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"    → Normal distribution (p ≥ 0.05)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Normality Tests (Shapiro-Wilk):
  Fiction: W = 0.9827, p = 0.6722
    → Normal distribution (p ≥ 0.05)
  Academic: W = 0.9713, p = 0.2616
    → Normal distribution (p ≥ 0.05)
  News: W = 0.9775, p = 0.4534
    → Normal distribution (p ≥ 0.05)</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>: p &gt; 0.05 suggests normality assumption is met. If p &lt; 0.05 but sample is large and distributions are symmetric, ANOVA still appropriate.</p>
</section>
<section id="homogeneity-of-variance" class="level3" data-number="9.7.3">
<h3 data-number="9.7.3" class="anchored" data-anchor-id="homogeneity-of-variance"><span class="header-section-number">9.7.3</span> 3. Homogeneity of Variance</h3>
<p><strong>Assumption</strong>: Variance is equal across groups (homoscedasticity).</p>
<p><strong>Violation</strong>: One group has much larger variance than others.</p>
<p><strong>Check</strong>: <strong>Levene’s test</strong> or variance ratio (largest SD / smallest SD &lt; 2).</p>
<p><strong>Robustness</strong>: ANOVA is robust if group sizes are equal. Violated assumption + unequal sizes = unreliable.</p>
<p><strong>Alternative</strong>: If violated, use <strong>Welch’s ANOVA</strong> (doesn’t assume equal variances).</p>
<div id="586928d4" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Levene's test for homogeneity of variance</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> levene</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>fiction <span class="op">=</span> data.<span class="bu">filter</span>(pl.col(<span class="st">'genre'</span>) <span class="op">==</span> <span class="st">'Fiction'</span>).select(<span class="st">'dimension_1'</span>).to_numpy().flatten()</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>academic <span class="op">=</span> data.<span class="bu">filter</span>(pl.col(<span class="st">'genre'</span>) <span class="op">==</span> <span class="st">'Academic'</span>).select(<span class="st">'dimension_1'</span>).to_numpy().flatten()</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>news <span class="op">=</span> data.<span class="bu">filter</span>(pl.col(<span class="st">'genre'</span>) <span class="op">==</span> <span class="st">'News'</span>).select(<span class="st">'dimension_1'</span>).to_numpy().flatten()</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>stat, p <span class="op">=</span> levene(fiction, academic, news)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Levene's Test for Homogeneity of Variance:"</span>)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  W = </span><span class="sc">{</span>stat<span class="sc">:.4f}</span><span class="ss">, p = </span><span class="sc">{</span>p<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> p <span class="op">&lt;</span> <span class="fl">0.05</span>:</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  → Variances differ significantly (p &lt; 0.05)"</span>)</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  → Consider Welch's ANOVA or transformation"</span>)</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  → Homogeneity assumption met (p ≥ 0.05)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Levene's Test for Homogeneity of Variance:
  W = 6.1480, p = 0.0027
  → Variances differ significantly (p &lt; 0.05)
  → Consider Welch's ANOVA or transformation</code></pre>
</div>
</div>
</section>
<section id="welchs-anova-robust-alternative" class="level3" data-number="9.7.4">
<h3 data-number="9.7.4" class="anchored" data-anchor-id="welchs-anova-robust-alternative"><span class="header-section-number">9.7.4</span> Welch’s ANOVA (Robust Alternative)</h3>
<div id="adab110b" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Welch's ANOVA (doesn't assume equal variances)</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Note: scipy doesn't have built-in Welch ANOVA, but we can use statsmodels</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># For demonstration, show concept</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Welch's ANOVA (if Levene's test failed):"</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  Use this when groups have unequal variances"</span>)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  Similar to regular ANOVA but adjusts degrees of freedom"</span>)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  Generally more robust for real-world data"</span>)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="co"># scipy.stats doesn't have Welch ANOVA; use regular ANOVA if variances are reasonable</span></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Or use statsmodels or pingouin package for Welch's test</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Welch's ANOVA (if Levene's test failed):
  Use this when groups have unequal variances
  Similar to regular ANOVA but adjusts degrees of freedom
  Generally more robust for real-world data</code></pre>
</div>
</div>
</section>
</section>
<section id="reporting-results" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="reporting-results"><span class="header-section-number">9.8</span> Reporting Results</h2>
<section id="apa-style" class="level3" data-number="9.8.1">
<h3 data-number="9.8.1" class="anchored" data-anchor-id="apa-style"><span class="header-section-number">9.8.1</span> APA Style</h3>
<p><strong>Example</strong> (for publication):</p>
<blockquote class="blockquote">
<p>A one-way analysis of variance (ANOVA) tested whether genres differed on Dimension 1 (Involved vs.&nbsp;Informational Production). Results showed significant differences among Fiction, Academic, and News genres, <em>F</em>(2, 147) = 183.2, <em>p</em> &lt; .001, η² = .71. Post-hoc comparisons using Tukey’s HSD indicated that all three genres differed significantly (all <em>p</em>s &lt; .001). Fiction texts scored highest (M = 15.2, SD = 5.1), followed by News (M = 2.1, SD = 6.0), with Academic texts scoring lowest (M = -12.1, SD = 4.3). Genre membership explained 71% of the variance in Dimension 1 scores, indicating that this dimension is a robust marker of genre differences.</p>
</blockquote>
<p><strong>Components</strong>:</p>
<ol type="1">
<li><strong>Test type</strong>: One-way ANOVA</li>
<li><strong>What was tested</strong>: Dimension 1 across genres</li>
<li><strong>F-statistic with df</strong>: F(2, 147) = 183.2</li>
<li><strong>P-value</strong>: p &lt; .001 (exact p if &gt; .001)</li>
<li><strong>Effect size</strong>: η² = .71</li>
<li><strong>Post-hoc results</strong>: Which pairs differ (Tukey’s HSD)</li>
<li><strong>Descriptive statistics</strong>: Means and SDs for each group</li>
<li><strong>Interpretation</strong>: What the effect size means substantively</li>
</ol>
</section>
<section id="in-tables" class="level3" data-number="9.8.2">
<h3 data-number="9.8.2" class="anchored" data-anchor-id="in-tables"><span class="header-section-number">9.8.2</span> In Tables</h3>
<p><strong>Table 1: ANOVA Results for MDA Dimensions</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 27%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>F(df1, df2)</th>
<th>p</th>
<th>η²</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dimension 1: Involved vs.&nbsp;Informational</td>
<td>183.2 (2, 147)</td>
<td>&lt;.001</td>
<td>.71</td>
<td>Large effect; strong genre marker</td>
</tr>
<tr class="even">
<td>Dimension 2: Narrative vs.&nbsp;Non-narrative</td>
<td>45.6 (2, 147)</td>
<td>&lt;.001</td>
<td>.38</td>
<td>Large effect; distinguishes fiction</td>
</tr>
<tr class="odd">
<td>Dimension 3: Abstract vs.&nbsp;Concrete</td>
<td>12.3 (2, 147)</td>
<td>&lt;.001</td>
<td>.14</td>
<td>Medium effect; weak differentiation</td>
</tr>
</tbody>
</table>
<p><strong>Table 2: Genre Means by Dimension</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 30%">
<col style="width: 30%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Genre</th>
<th>Dimension 1 (M, SD)</th>
<th>Dimension 2 (M, SD)</th>
<th>Dimension 3 (M, SD)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fiction</td>
<td>15.2 (5.1)</td>
<td>14.3 (4.8)</td>
<td>-2.1 (3.9)</td>
</tr>
<tr class="even">
<td>Academic</td>
<td>-12.1 (4.3)</td>
<td>-5.2 (5.1)</td>
<td>11.8 (4.2)</td>
</tr>
<tr class="odd">
<td>News</td>
<td>2.1 (6.0)</td>
<td>3.9 (5.4)</td>
<td>1.2 (4.5)</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="connections-to-other-methods" class="level2" data-number="9.9">
<h2 data-number="9.9" class="anchored" data-anchor-id="connections-to-other-methods"><span class="header-section-number">9.9</span> Connections to Other Methods</h2>
<section id="anova-and-mda" class="level3" data-number="9.9.1">
<h3 data-number="9.9.1" class="anchored" data-anchor-id="anova-and-mda"><span class="header-section-number">9.9.1</span> ANOVA and MDA</h3>
<p><strong>Standard MDA workflow</strong>:</p>
<ol type="1">
<li>Extract dimensions (Factor Analysis or PCA)</li>
<li>Compute dimension scores for each text</li>
<li><strong>ANOVA</strong>: Test if genres differ on each dimension</li>
<li><strong>R²/η²</strong>: Quantify how much genre explains variance</li>
<li><strong>Post-hoc</strong>: Identify which genre pairs differ</li>
</ol>
<p><strong>Why this matters</strong>: Dimensions are only useful if they distinguish categories. ANOVA + R² validate that extracted dimensions are meaningful.</p>
<p><strong>Example</strong>: If Dimension 1 has η² &lt; 0.05, it captures individual variation (stylistic idiosyncrasies) but not genre patterns. Consider dropping or reinterpreting.</p>
</section>
<section id="anova-and-classification" class="level3" data-number="9.9.2">
<h3 data-number="9.9.2" class="anchored" data-anchor-id="anova-and-classification"><span class="header-section-number">9.9.2</span> ANOVA and Classification</h3>
<p><strong>Feature selection</strong>:</p>
<ul>
<li>Use ANOVA to identify which features differ significantly across classes</li>
<li>Select features with high F-statistics and η² for classification models</li>
<li>Reduces dimensionality (keep only discriminating features)</li>
</ul>
<p><strong>Example</strong>: You have 67 linguistic features. ANOVA shows 15 have η² &gt; 0.10 for genre. Use those 15 as classifier inputs.</p>
</section>
<section id="anova-and-regression" class="level3" data-number="9.9.3">
<h3 data-number="9.9.3" class="anchored" data-anchor-id="anova-and-regression"><span class="header-section-number">9.9.3</span> ANOVA and Regression</h3>
<p><strong>R² in regression</strong> measures variance explained by predictor(s):</p>
<p><span class="math display">\[R^2 = 1 - \frac{SS_{residual}}{SS_{total}}\]</span></p>
<p><strong>In ANOVA context</strong>:</p>
<ul>
<li>Single categorical predictor (genre) → R² = η²</li>
<li>Continuous predictor (word length) → R² from linear regression</li>
<li>Multiple predictors → Multiple R²</li>
</ul>
<p><strong>Connection</strong>: ANOVA is a special case of regression where predictors are categorical.</p>
</section>
<section id="anova-and-time-series" class="level3" data-number="9.9.4">
<h3 data-number="9.9.4" class="anchored" data-anchor-id="anova-and-time-series"><span class="header-section-number">9.9.4</span> ANOVA and Time Series</h3>
<p><strong>Diachronic analysis</strong>: Do linguistic features change across time periods?</p>
<p><strong>Application</strong>:</p>
<ol type="1">
<li>Bin texts by decade (1800s, 1900s, 2000s)</li>
<li>Compute feature rates (e.g., passive frequency)</li>
<li>ANOVA: Does passive rate differ by decade?</li>
<li>R²: How much temporal variation is explained?</li>
</ol>
<p><strong>Example</strong>: If η² = 0.45 for “passives across centuries,” historical period explains nearly half the variation—strong evidence of language change.</p>
</section>
</section>
<section id="methodological-considerations" class="level2" data-number="9.10">
<h2 data-number="9.10" class="anchored" data-anchor-id="methodological-considerations"><span class="header-section-number">9.10</span> Methodological Considerations</h2>
<section id="sample-size" class="level3" data-number="9.10.1">
<h3 data-number="9.10.1" class="anchored" data-anchor-id="sample-size"><span class="header-section-number">9.10.1</span> 1. Sample Size</h3>
<p><strong>Minimum</strong>: 20-30 observations per group for reliable results.</p>
<p><strong>Power</strong>: Larger samples detect smaller effects. With n = 500 per group, even η² = 0.02 is detectable.</p>
<p><strong>Balance</strong>: Equal group sizes maximize power. Unequal sizes (50 vs.&nbsp;500) reduce ability to detect differences.</p>
<p><strong>In text analysis</strong>: Aim for balanced sampling (50 fiction, 50 academic, 50 news) rather than opportunistic corpora (500 fiction, 12 academic).</p>
</section>
<section id="multiple-testing" class="level3" data-number="9.10.2">
<h3 data-number="9.10.2" class="anchored" data-anchor-id="multiple-testing"><span class="header-section-number">9.10.2</span> 2. Multiple Testing</h3>
<p><strong>Problem</strong>: Testing 10 dimensions across 5 genres = 10 ANOVAs. Chance of false positive increases.</p>
<p><strong>Solution</strong>:</p>
<ul>
<li><strong>Bonferroni correction</strong>: Divide α by number of tests (0.05 / 10 = 0.005)</li>
<li><strong>False Discovery Rate (FDR)</strong>: Controls expected proportion of false positives (less conservative)</li>
<li><strong>Pre-registration</strong>: Specify which tests are confirmatory vs.&nbsp;exploratory</li>
</ul>
</section>
<section id="practical-vs.-statistical-significance" class="level3" data-number="9.10.3">
<h3 data-number="9.10.3" class="anchored" data-anchor-id="practical-vs.-statistical-significance"><span class="header-section-number">9.10.3</span> 3. Practical vs.&nbsp;Statistical Significance</h3>
<p><strong>Large samples</strong> (n &gt; 1000): Tiny effects become “significant” (p &lt; 0.05) even if meaningless.</p>
<p><strong>Example</strong>: η² = 0.008 (0.8% variance explained) with p &lt; 0.001. Statistically significant but trivial effect.</p>
<p><strong>Best practice</strong>: Always report effect size (η², not just p-value). Focus on η² &gt; 0.06 (medium+) for substantive claims.</p>
</section>
<section id="nested-data" class="level3" data-number="9.10.4">
<h3 data-number="9.10.4" class="anchored" data-anchor-id="nested-data"><span class="header-section-number">9.10.4</span> 4. Nested Data</h3>
<p><strong>Problem</strong>: Texts aren’t truly independent (multiple texts per author, per time period).</p>
<p><strong>Example</strong>: 50 fiction texts by 5 authors (10 texts each). Texts by same author are correlated (shared style).</p>
<p><strong>Solution</strong>: <strong>Mixed-effects models</strong> or <strong>nested ANOVA</strong> accounting for clustering:</p>
<ul>
<li>Level 1: Texts</li>
<li>Level 2: Authors</li>
<li>Level 3: Genres</li>
</ul>
<p><strong>In Python</strong>: Use <code>statsmodels.MixedLM</code> or <code>pymer4</code>.</p>
</section>
</section>
<section id="ethical-considerations" class="level2" data-number="9.11">
<h2 data-number="9.11" class="anchored" data-anchor-id="ethical-considerations"><span class="header-section-number">9.11</span> Ethical Considerations</h2>
<section id="p-hacking" class="level3" data-number="9.11.1">
<h3 data-number="9.11.1" class="anchored" data-anchor-id="p-hacking"><span class="header-section-number">9.11.1</span> 1. P-Hacking</h3>
<p><strong>Risk</strong>: Running many ANOVAs, reporting only significant ones.</p>
<p><strong>Example</strong>: Test 50 dimensions, report the 5 with p &lt; 0.05 (ignoring 45 non-significant tests).</p>
<p><strong>Solution</strong>: Pre-register analyses, report all tests, or adjust α for multiple comparisons.</p>
</section>
<section id="harking-hypothesizing-after-results-known" class="level3" data-number="9.11.2">
<h3 data-number="9.11.2" class="anchored" data-anchor-id="harking-hypothesizing-after-results-known"><span class="header-section-number">9.11.2</span> 2. HARKing (Hypothesizing After Results Known)</h3>
<p><strong>Risk</strong>: Presenting post-hoc patterns as if they were predicted a priori.</p>
<p><strong>Example</strong>: Dimension 3 unexpectedly distinguishes Government from News. Retroactively claim you hypothesized this (you didn’t).</p>
<p><strong>Solution</strong>: Distinguish exploratory from confirmatory findings. Exploratory findings are valuable but need replication.</p>
</section>
<section id="overgeneralizing" class="level3" data-number="9.11.3">
<h3 data-number="9.11.3" class="anchored" data-anchor-id="overgeneralizing"><span class="header-section-number">9.11.3</span> 3. Overgeneralizing</h3>
<p><strong>Risk</strong>: Assuming patterns in one corpus apply universally.</p>
<p><strong>Example</strong>: “Academic writing is always highly informational (η² = 0.60 in my corpus of chemistry papers).” But humanities papers might differ.</p>
<p><strong>Solution</strong>: Specify corpus boundaries. Replicate across multiple corpora before generalizing.</p>
</section>
<section id="ignoring-context" class="level3" data-number="9.11.4">
<h3 data-number="9.11.4" class="anchored" data-anchor-id="ignoring-context"><span class="header-section-number">9.11.4</span> 4. Ignoring Context</h3>
<p><strong>Risk</strong>: Treating statistical differences as natural categories.</p>
<p><strong>Example</strong>: Fiction scores +15, Academic -12 on Dimension 1. Concluding “Fiction is fundamentally different from Academic writing” ignores historical, social, and institutional forces shaping these genres.</p>
<p><strong>Solution</strong>: Statistical patterns describe, they don’t explain. Combine quantitative findings with qualitative interpretation and theoretical framing.</p>
</section>
</section>
<section id="summary" class="level2" data-number="9.12">
<h2 data-number="9.12" class="anchored" data-anchor-id="summary"><span class="header-section-number">9.12</span> Summary</h2>
<p><strong>ANOVA</strong> (Analysis of Variance) tests if group means differ significantly:</p>
<ul>
<li><strong>F-statistic</strong>: Ratio of between-group to within-group variance</li>
<li><strong>P-value</strong>: Probability groups differ by chance (p &lt; 0.05 = significant)</li>
<li><strong>Assumptions</strong>: Independence, normality, homogeneity of variance</li>
</ul>
<p><strong>R²/η²</strong> (coefficient of determination/eta-squared) quantifies proportion of variance explained:</p>
<ul>
<li><strong>Formula</strong>: η² = SS_between / SS_total</li>
<li><strong>Interpretation</strong>: 0 to 1 (0% to 100% variance explained)</li>
<li><strong>Effect sizes</strong>: Small (0.01), Medium (0.06), Large (0.14)</li>
</ul>
<p><strong>In MDA context</strong>:</p>
<ul>
<li>After extracting dimensions, ANOVA tests if they distinguish genres</li>
<li>η² shows which dimensions are strong vs.&nbsp;weak category markers</li>
<li>Post-hoc tests (Tukey, Bonferroni) identify which specific pairs differ</li>
</ul>
<p><strong>Key insights</strong>:</p>
<ol type="1">
<li><strong>Variance decomposition</strong>: Total variance = between-group + within-group</li>
<li><strong>F-statistic</strong>: MS_between / MS_within (large F = strong evidence of differences)</li>
<li><strong>Effect size matters</strong>: Report η², not just p-values (practical vs.&nbsp;statistical significance)</li>
<li><strong>Assumptions</strong>: Check normality, homogeneity; use robust alternatives if violated</li>
<li><strong>Multiple comparisons</strong>: Adjust α when testing many groups/dimensions</li>
</ol>
<p><strong>Best practices</strong>:</p>
<ul>
<li>Report full ANOVA table (SS, df, MS, F, p, η²)</li>
<li>Include descriptive statistics (means, SDs by group)</li>
<li>Use post-hoc tests for pairwise comparisons</li>
<li>Report effect sizes, not just significance</li>
<li>Check assumptions; use robust methods if violated</li>
</ul>
<p><strong>Next steps</strong>: Apply ANOVA to your MDA results. Test which dimensions distinguish genres, quantify effect sizes, identify specific group differences. Combine statistical tests with substantive interpretation grounded in linguistic theory.</p>
</section>
<section id="further-reading" class="level2" data-number="9.13">
<h2 data-number="9.13" class="anchored" data-anchor-id="further-reading"><span class="header-section-number">9.13</span> Further Reading</h2>
<p><strong>Foundational:</strong></p>
<ul>
<li>Cohen, J. (1988). <em>Statistical Power Analysis for the Behavioral Sciences</em> (2nd ed.). Routledge. (Effect sizes, power)</li>
<li>Field, A., Miles, J., &amp; Field, Z. (2012). <em>Discovering Statistics Using R</em>. Sage. (Chapter 10: ANOVA)</li>
</ul>
<p><strong>ANOVA specifics:</strong></p>
<ul>
<li>Maxwell, S. E., &amp; Delaney, H. D. (2004). <em>Designing Experiments and Analyzing Data</em> (2nd ed.). Psychology Press. (Comprehensive ANOVA coverage)</li>
<li>Keppel, G., &amp; Wickens, T. D. (2004). <em>Design and Analysis: A Researcher’s Handbook</em> (4th ed.). Pearson. (Experimental design, post-hoc tests)</li>
</ul>
<p><strong>Effect sizes:</strong></p>
<ul>
<li>Lakens, D. (2013). Calculating and reporting effect sizes to facilitate cumulative science. <em>Frontiers in Psychology</em>, 4, 863. <a href="https://doi.org/10.3389/fpsyg.2013.00863">DOI</a></li>
<li>Fritz, C. O., Morris, P. E., &amp; Richler, J. J. (2012). Effect size estimates: Current use, calculations, and interpretation. <em>Journal of Experimental Psychology: General</em>, 141(1), 2-18. <a href="https://doi.org/10.1037/a0024338">DOI</a></li>
</ul>
<p><strong>MDA applications:</strong></p>
<ul>
<li>Biber, D. (1988). <em>Variation Across Speech and Writing</em>. Cambridge University Press. (Foundational MDA, uses ANOVA to validate dimensions)</li>
<li>Biber, D., &amp; Conrad, S. (2009). <em>Register, Genre, and Style</em>. Cambridge University Press. (Chapter 6: MDA methodology)</li>
</ul>
<p><strong>Practical guides:</strong></p>
<ul>
<li>Scipy documentation: <a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.f_oneway.html">scipy.stats.f_oneway</a></li>
<li>Statsmodels: <a href="https://www.statsmodels.org/stable/anova.html">ANOVA</a></li>
<li>Pingouin: <a href="https://pingouin-stats.org/api.html#anova">ANOVA and post-hoc tests</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../tutorials/topic-modeling.html" class="pagination-link" aria-label="Topic Modeling">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Topic Modeling</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../tutorials/cluster-analysis.html" class="pagination-link" aria-label="Clustering Methods">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Clustering Methods</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/browndw/humanities_analytics/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>